add pyproject.toml for numpy requirement
readbeyond/aeneas pull request #272
Opened 2021-04-16 01:56 UTC by valrus

This PR adds a pyproject.toml file to address the need to manually install numpy before aeneas, which was preventing aeneas from installing correctly in a Heroku app.

I took the approach from [this PR](https://github.com/prody/ProDy/pull/806) on a project with the same issue. Based on the comments on that PR, it should work for any version of pip above 10 and be harmless for lower versions. I tested it in a Heroku deploy and was able to install aeneas directly from a requirements.txt file.

2023-07-06 13:10 UTC, danielbair approved these changes

2025-03-10 23:56 UTC, EthanShoeDev commented
A recent update to setuptools broke this fix for me. I created a fork that fixes the issue by pinning setuptools to 75.8.x

2026-07-22 16:37 UTC, readbeyond commented
@valrus please open the PR against the ``develop`` branch, not directly ``master``. Also incorporate the https://github.com/readbeyond/aeneas/pull/272#issuecomment-2712107678 and test if ``setuptools`` must be pinned.

2026-07-22 16:40 UTC, readbeyond commented on pyproject.toml
> +requires = ["setuptools", "wheel", "numpy>=1.9"]
Please incorporate the https://github.com/readbeyond/aeneas/pull/272#issuecomment-2712107678 and test if pinned setuptools indeed works.

2026-07-22 16:41 UTC, readbeyond commented on MANIFEST.in
> +include pyproject.toml
Please open the PR against the ``develop`` branch, not directly ``master``.

2026-07-22 16:41 UTC, readbeyond requested changes

2026-07-25 08:55 UTC, readbeyond commented on MANIFEST.in
> +include pyproject.toml
@valrus I went ahead and changed it by editing the PR.

2026-07-25 08:56 UTC, readbeyond commented on pyproject.toml
> +requires = ["setuptools", "wheel", "numpy>=1.9"]
@valrus I go ahead and merge your PR. I will verify the remark about pinning `setuptools` ( https://github.com/readbeyond/aeneas/pull/272#issuecomment-2712107678 ) myself, and in case push an additional commit to `devel`.

2026-07-25 08:57 UTC, readbeyond approved these changes

2026-07-25 08:57 UTC, merged